# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imNEU.ui'
#
# Created: Tue Nov  7 10:17:20 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_imneu_mainwindow(object):
    def setupUi(self, imneu_mainwindow):
        imneu_mainwindow.setObjectName(_fromUtf8("imneu_mainwindow"))
        imneu_mainwindow.resize(800, 600)
        imneu_mainwindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        imneu_mainwindow.setAutoFillBackground(False)
        imneu_mainwindow.setStyleSheet(_fromUtf8("background-color: rgb(85, 170, 127);"))
        self.centralwidget = QtGui.QWidget(imneu_mainwindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 60, 671, 491))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans Fallback"))
        font.setPointSize(14)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 121, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(360, 40, 131, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(510, 90, 71, 151))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lineEdit_right_elbow = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_right_elbow.setObjectName(_fromUtf8("lineEdit_right_elbow"))
        self.verticalLayout_3.addWidget(self.lineEdit_right_elbow)
        self.lineEdit_right_shoulder_L = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_right_shoulder_L.setObjectName(_fromUtf8("lineEdit_right_shoulder_L"))
        self.verticalLayout_3.addWidget(self.lineEdit_right_shoulder_L)
        self.lineEdit_right_shoulder_M = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_right_shoulder_M.setObjectName(_fromUtf8("lineEdit_right_shoulder_M"))
        self.verticalLayout_3.addWidget(self.lineEdit_right_shoulder_M)
        self.lineEdit_right_shoulder_U = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_right_shoulder_U.setObjectName(_fromUtf8("lineEdit_right_shoulder_U"))
        self.verticalLayout_3.addWidget(self.lineEdit_right_shoulder_U)
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(390, 90, 121, 151))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.right_elbow_joint = QtGui.QSlider(self.layoutWidget_2)
        self.right_elbow_joint.setMinimum(23)
        self.right_elbow_joint.setMaximum(100)
        self.right_elbow_joint.setOrientation(QtCore.Qt.Horizontal)
        self.right_elbow_joint.setObjectName(_fromUtf8("right_elbow_joint"))
        self.verticalLayout_4.addWidget(self.right_elbow_joint)
        self.right_shoulder_L = QtGui.QSlider(self.layoutWidget_2)
        self.right_shoulder_L.setMinimum(10)
        self.right_shoulder_L.setMaximum(170)
        self.right_shoulder_L.setSliderPosition(95)
        self.right_shoulder_L.setOrientation(QtCore.Qt.Horizontal)
        self.right_shoulder_L.setObjectName(_fromUtf8("right_shoulder_L"))
        self.verticalLayout_4.addWidget(self.right_shoulder_L)
        self.right_shoulder_M = QtGui.QSlider(self.layoutWidget_2)
        self.right_shoulder_M.setMinimum(20)
        self.right_shoulder_M.setMaximum(100)
        self.right_shoulder_M.setOrientation(QtCore.Qt.Horizontal)
        self.right_shoulder_M.setObjectName(_fromUtf8("right_shoulder_M"))
        self.verticalLayout_4.addWidget(self.right_shoulder_M)
        self.right_shoulder_U = QtGui.QSlider(self.layoutWidget_2)
        self.right_shoulder_U.setMinimum(10)
        self.right_shoulder_U.setMaximum(80)
        self.right_shoulder_U.setOrientation(QtCore.Qt.Horizontal)
        self.right_shoulder_U.setObjectName(_fromUtf8("right_shoulder_U"))
        self.verticalLayout_4.addWidget(self.right_shoulder_U)
        self.joint_angle_reset_button = QtGui.QPushButton(self.tab)
        self.joint_angle_reset_button.setGeometry(QtCore.QRect(230, 260, 98, 27))
        self.joint_angle_reset_button.setObjectName(_fromUtf8("joint_angle_reset_button"))
        self.joint_angle_excute_button = QtGui.QPushButton(self.tab)
        self.joint_angle_excute_button.setGeometry(QtCore.QRect(230, 300, 98, 27))
        self.joint_angle_excute_button.setObjectName(_fromUtf8("joint_angle_excute_button"))
        self.textEdit = QtGui.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(80, 340, 451, 111))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.layoutWidget1 = QtGui.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(70, 90, 121, 151))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.left_elbow_joint = QtGui.QSlider(self.layoutWidget1)
        self.left_elbow_joint.setMinimum(60)
        self.left_elbow_joint.setMaximum(150)
        self.left_elbow_joint.setSingleStep(0)
        self.left_elbow_joint.setOrientation(QtCore.Qt.Horizontal)
        self.left_elbow_joint.setObjectName(_fromUtf8("left_elbow_joint"))
        self.verticalLayout.addWidget(self.left_elbow_joint)
        self.left_shoulder_joint_L = QtGui.QSlider(self.layoutWidget1)
        self.left_shoulder_joint_L.setMinimum(20)
        self.left_shoulder_joint_L.setMaximum(170)
        self.left_shoulder_joint_L.setSliderPosition(90)
        self.left_shoulder_joint_L.setOrientation(QtCore.Qt.Horizontal)
        self.left_shoulder_joint_L.setObjectName(_fromUtf8("left_shoulder_joint_L"))
        self.verticalLayout.addWidget(self.left_shoulder_joint_L)
        self.left_shoulder_joint_M = QtGui.QSlider(self.layoutWidget1)
        self.left_shoulder_joint_M.setMinimum(15)
        self.left_shoulder_joint_M.setMaximum(90)
        self.left_shoulder_joint_M.setOrientation(QtCore.Qt.Horizontal)
        self.left_shoulder_joint_M.setObjectName(_fromUtf8("left_shoulder_joint_M"))
        self.verticalLayout.addWidget(self.left_shoulder_joint_M)
        self.left_shoulder_joint_U = QtGui.QSlider(self.layoutWidget1)
        self.left_shoulder_joint_U.setMinimum(16)
        self.left_shoulder_joint_U.setMaximum(80)
        self.left_shoulder_joint_U.setOrientation(QtCore.Qt.Horizontal)
        self.left_shoulder_joint_U.setObjectName(_fromUtf8("left_shoulder_joint_U"))
        self.verticalLayout.addWidget(self.left_shoulder_joint_U)
        self.layoutWidget2 = QtGui.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(190, 90, 111, 151))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit_left_elbow = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_left_elbow.setObjectName(_fromUtf8("lineEdit_left_elbow"))
        self.verticalLayout_2.addWidget(self.lineEdit_left_elbow)
        self.lineEdit_left_shoulder_L = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_left_shoulder_L.setObjectName(_fromUtf8("lineEdit_left_shoulder_L"))
        self.verticalLayout_2.addWidget(self.lineEdit_left_shoulder_L)
        self.lineEdit_left_shoulder_M = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_left_shoulder_M.setObjectName(_fromUtf8("lineEdit_left_shoulder_M"))
        self.verticalLayout_2.addWidget(self.lineEdit_left_shoulder_M)
        self.lineEdit_left_shoulder_U = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_left_shoulder_U.setObjectName(_fromUtf8("lineEdit_left_shoulder_U"))
        self.verticalLayout_2.addWidget(self.lineEdit_left_shoulder_U)
        self.layoutWidget3 = QtGui.QWidget(self.tab)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 90, 61, 151))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_11.setMargin(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_11.addWidget(self.label_6)
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_11.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_11.addWidget(self.label_8)
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_11.addWidget(self.label_7)
        self.layoutWidget4 = QtGui.QWidget(self.tab)
        self.layoutWidget4.setGeometry(QtCore.QRect(330, 90, 61, 151))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_13 = QtGui.QLabel(self.layoutWidget4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_12.addWidget(self.label_13)
        self.label_12 = QtGui.QLabel(self.layoutWidget4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_12.addWidget(self.label_12)
        self.label_11 = QtGui.QLabel(self.layoutWidget4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_12.addWidget(self.label_11)
        self.label_10 = QtGui.QLabel(self.layoutWidget4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_12.addWidget(self.label_10)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 66, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(370, 40, 66, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textEdit_2 = QtGui.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 370, 551, 78))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.cartesian_reset_button = QtGui.QPushButton(self.tab_2)
        self.cartesian_reset_button.setGeometry(QtCore.QRect(230, 190, 98, 27))
        self.cartesian_reset_button.setObjectName(_fromUtf8("cartesian_reset_button"))
        self.cartesian_excute_button = QtGui.QPushButton(self.tab_2)
        self.cartesian_excute_button.setGeometry(QtCore.QRect(230, 220, 98, 27))
        self.cartesian_excute_button.setObjectName(_fromUtf8("cartesian_excute_button"))
        self.layoutWidget5 = QtGui.QWidget(self.tab_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 80, 141, 101))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.left_cartesian_x = QtGui.QSlider(self.layoutWidget5)
        self.left_cartesian_x.setMinimum(-200)
        self.left_cartesian_x.setMaximum(642)
        self.left_cartesian_x.setPageStep(5)
        self.left_cartesian_x.setProperty("value", 73)
        self.left_cartesian_x.setSliderPosition(73)
        self.left_cartesian_x.setOrientation(QtCore.Qt.Horizontal)
        self.left_cartesian_x.setObjectName(_fromUtf8("left_cartesian_x"))
        self.verticalLayout_5.addWidget(self.left_cartesian_x)
        self.left_cartesian_y = QtGui.QSlider(self.layoutWidget5)
        self.left_cartesian_y.setMinimum(43)
        self.left_cartesian_y.setMaximum(613)
        self.left_cartesian_y.setPageStep(5)
        self.left_cartesian_y.setSliderPosition(572)
        self.left_cartesian_y.setOrientation(QtCore.Qt.Horizontal)
        self.left_cartesian_y.setObjectName(_fromUtf8("left_cartesian_y"))
        self.verticalLayout_5.addWidget(self.left_cartesian_y)
        self.left_cartesian_z = QtGui.QSlider(self.layoutWidget5)
        self.left_cartesian_z.setMaximum(613)
        self.left_cartesian_z.setPageStep(5)
        self.left_cartesian_z.setSliderPosition(150)
        self.left_cartesian_z.setOrientation(QtCore.Qt.Horizontal)
        self.left_cartesian_z.setObjectName(_fromUtf8("left_cartesian_z"))
        self.verticalLayout_5.addWidget(self.left_cartesian_z)
        self.layoutWidget6 = QtGui.QWidget(self.tab_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(80, 190, 131, 128))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lineEdit_left_elbow_display = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_left_elbow_display.setObjectName(_fromUtf8("lineEdit_left_elbow_display"))
        self.verticalLayout_6.addWidget(self.lineEdit_left_elbow_display)
        self.lineEdit_left_shoulder1_display = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_left_shoulder1_display.setObjectName(_fromUtf8("lineEdit_left_shoulder1_display"))
        self.verticalLayout_6.addWidget(self.lineEdit_left_shoulder1_display)
        self.lineEdit_left_shoulder2_display = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_left_shoulder2_display.setObjectName(_fromUtf8("lineEdit_left_shoulder2_display"))
        self.verticalLayout_6.addWidget(self.lineEdit_left_shoulder2_display)
        self.lineEdit_left_shoulder3_display = QtGui.QLineEdit(self.layoutWidget6)
        self.lineEdit_left_shoulder3_display.setObjectName(_fromUtf8("lineEdit_left_shoulder3_display"))
        self.verticalLayout_6.addWidget(self.lineEdit_left_shoulder3_display)
        self.layoutWidget7 = QtGui.QWidget(self.tab_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(360, 80, 151, 101))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.right_cartesian_x = QtGui.QSlider(self.layoutWidget7)
        self.right_cartesian_x.setMinimum(73)
        self.right_cartesian_x.setMaximum(643)
        self.right_cartesian_x.setOrientation(QtCore.Qt.Horizontal)
        self.right_cartesian_x.setObjectName(_fromUtf8("right_cartesian_x"))
        self.verticalLayout_7.addWidget(self.right_cartesian_x)
        self.right_cartesian_y = QtGui.QSlider(self.layoutWidget7)
        self.right_cartesian_y.setMinimum(43)
        self.right_cartesian_y.setMaximum(613)
        self.right_cartesian_y.setSliderPosition(572)
        self.right_cartesian_y.setOrientation(QtCore.Qt.Horizontal)
        self.right_cartesian_y.setObjectName(_fromUtf8("right_cartesian_y"))
        self.verticalLayout_7.addWidget(self.right_cartesian_y)
        self.right_cartesian_z = QtGui.QSlider(self.layoutWidget7)
        self.right_cartesian_z.setMaximum(613)
        self.right_cartesian_z.setSliderPosition(150)
        self.right_cartesian_z.setOrientation(QtCore.Qt.Horizontal)
        self.right_cartesian_z.setObjectName(_fromUtf8("right_cartesian_z"))
        self.verticalLayout_7.addWidget(self.right_cartesian_z)
        self.layoutWidget8 = QtGui.QWidget(self.tab_2)
        self.layoutWidget8.setGeometry(QtCore.QRect(410, 190, 131, 128))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lineEdit_right_elbow_display = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit_right_elbow_display.setObjectName(_fromUtf8("lineEdit_right_elbow_display"))
        self.verticalLayout_8.addWidget(self.lineEdit_right_elbow_display)
        self.lineEdit_right_shoulder1_display = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit_right_shoulder1_display.setObjectName(_fromUtf8("lineEdit_right_shoulder1_display"))
        self.verticalLayout_8.addWidget(self.lineEdit_right_shoulder1_display)
        self.lineEdit_right_shoulder2_display = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit_right_shoulder2_display.setObjectName(_fromUtf8("lineEdit_right_shoulder2_display"))
        self.verticalLayout_8.addWidget(self.lineEdit_right_shoulder2_display)
        self.lineEdit_right_shoulder3_display = QtGui.QLineEdit(self.layoutWidget8)
        self.lineEdit_right_shoulder3_display.setObjectName(_fromUtf8("lineEdit_right_shoulder3_display"))
        self.verticalLayout_8.addWidget(self.lineEdit_right_shoulder3_display)
        self.layoutWidget9 = QtGui.QWidget(self.tab_2)
        self.layoutWidget9.setGeometry(QtCore.QRect(170, 80, 81, 101))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lineEdit_left_cartesian_x = QtGui.QLineEdit(self.layoutWidget9)
        self.lineEdit_left_cartesian_x.setText(_fromUtf8(""))
        self.lineEdit_left_cartesian_x.setObjectName(_fromUtf8("lineEdit_left_cartesian_x"))
        self.verticalLayout_9.addWidget(self.lineEdit_left_cartesian_x)
        self.lineEdit_left_cartesian_y = QtGui.QLineEdit(self.layoutWidget9)
        self.lineEdit_left_cartesian_y.setObjectName(_fromUtf8("lineEdit_left_cartesian_y"))
        self.verticalLayout_9.addWidget(self.lineEdit_left_cartesian_y)
        self.lineEdit_left_cartesian_z = QtGui.QLineEdit(self.layoutWidget9)
        self.lineEdit_left_cartesian_z.setObjectName(_fromUtf8("lineEdit_left_cartesian_z"))
        self.verticalLayout_9.addWidget(self.lineEdit_left_cartesian_z)
        self.layoutWidget10 = QtGui.QWidget(self.tab_2)
        self.layoutWidget10.setGeometry(QtCore.QRect(509, 80, 81, 101))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.lineEdit_right_cartesian_x = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEdit_right_cartesian_x.setObjectName(_fromUtf8("lineEdit_right_cartesian_x"))
        self.verticalLayout_10.addWidget(self.lineEdit_right_cartesian_x)
        self.lineEdit_right_cartesian_y = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEdit_right_cartesian_y.setObjectName(_fromUtf8("lineEdit_right_cartesian_y"))
        self.verticalLayout_10.addWidget(self.lineEdit_right_cartesian_y)
        self.lineEdit_right_cartesian_z = QtGui.QLineEdit(self.layoutWidget10)
        self.lineEdit_right_cartesian_z.setObjectName(_fromUtf8("lineEdit_right_cartesian_z"))
        self.verticalLayout_10.addWidget(self.lineEdit_right_cartesian_z)
        self.layoutWidget11 = QtGui.QWidget(self.tab_2)
        self.layoutWidget11.setGeometry(QtCore.QRect(11, 80, 21, 101))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_14 = QtGui.QLabel(self.layoutWidget11)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_13.addWidget(self.label_14)
        self.label_17 = QtGui.QLabel(self.layoutWidget11)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_13.addWidget(self.label_17)
        self.label_16 = QtGui.QLabel(self.layoutWidget11)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_13.addWidget(self.label_16)
        self.layoutWidget12 = QtGui.QWidget(self.tab_2)
        self.layoutWidget12.setGeometry(QtCore.QRect(340, 80, 21, 101))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_15 = QtGui.QLabel(self.layoutWidget12)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_14.addWidget(self.label_15)
        self.label_19 = QtGui.QLabel(self.layoutWidget12)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_14.addWidget(self.label_19)
        self.label_18 = QtGui.QLabel(self.layoutWidget12)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_14.addWidget(self.label_18)
        self.layoutWidget13 = QtGui.QWidget(self.tab_2)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 190, 70, 121))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget13)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_20 = QtGui.QLabel(self.layoutWidget13)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_15.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.layoutWidget13)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_15.addWidget(self.label_21)
        self.label_23 = QtGui.QLabel(self.layoutWidget13)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_15.addWidget(self.label_23)
        self.label_22 = QtGui.QLabel(self.layoutWidget13)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_15.addWidget(self.label_22)
        self.layoutWidget14 = QtGui.QWidget(self.tab_2)
        self.layoutWidget14.setGeometry(QtCore.QRect(340, 190, 70, 121))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout_16.setMargin(0)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_24 = QtGui.QLabel(self.layoutWidget14)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_16.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(self.layoutWidget14)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_16.addWidget(self.label_25)
        self.label_27 = QtGui.QLabel(self.layoutWidget14)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_16.addWidget(self.label_27)
        self.label_26 = QtGui.QLabel(self.layoutWidget14)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_16.addWidget(self.label_26)
        self.lineEdit_mindistance_left = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_mindistance_left.setGeometry(QtCore.QRect(90, 340, 113, 27))
        self.lineEdit_mindistance_left.setCursorPosition(0)
        self.lineEdit_mindistance_left.setObjectName(_fromUtf8("lineEdit_mindistance_left"))
        self.lineEdit_min_distance_right = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_min_distance_right.setGeometry(QtCore.QRect(420, 340, 113, 27))
        self.lineEdit_min_distance_right.setObjectName(_fromUtf8("lineEdit_min_distance_right"))
        self.label_28 = QtGui.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(20, 340, 66, 17))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(350, 340, 66, 17))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.hand_open = QtGui.QPushButton(self.tab_2)
        self.hand_open.setGeometry(QtCore.QRect(230, 336, 98, 31))
        self.hand_open.setObjectName(_fromUtf8("hand_open"))
        self.hand_half_closed = QtGui.QPushButton(self.tab_2)
        self.hand_half_closed.setGeometry(QtCore.QRect(230, 250, 98, 31))
        self.hand_half_closed.setObjectName(_fromUtf8("hand_half_closed"))
        self.hand_closed = QtGui.QPushButton(self.tab_2)
        self.hand_closed.setGeometry(QtCore.QRect(230, 280, 98, 31))
        self.hand_closed.setObjectName(_fromUtf8("hand_closed"))
        self.fangzhi_zhunbei = QtGui.QPushButton(self.tab_2)
        self.fangzhi_zhunbei.setGeometry(QtCore.QRect(230, 310, 98, 27))
        self.fangzhi_zhunbei.setObjectName(_fromUtf8("fangzhi_zhunbei"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Droid Sans Fallback"))
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        imneu_mainwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(imneu_mainwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        imneu_mainwindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(imneu_mainwindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        imneu_mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(imneu_mainwindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(imneu_mainwindow)

    def retranslateUi(self, imneu_mainwindow):
        imneu_mainwindow.setWindowTitle(_translate("imneu_mainwindow", "MainWindow", None))
        self.label_2.setText(_translate("imneu_mainwindow", "左臂关节角度", None))
        self.label_3.setText(_translate("imneu_mainwindow", "右臂关节角度", None))
        self.joint_angle_reset_button.setText(_translate("imneu_mainwindow", "复位", None))
        self.joint_angle_excute_button.setText(_translate("imneu_mainwindow", "执行", None))
        self.textEdit.setHtml(_translate("imneu_mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans Fallback\'; font-size:11pt;\">帮助：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans Fallback\'; font-size:11pt;\">         滑动滑块可直接控制单个关节；输入数据点击执行可以控制多个关节；点击复位可以回到初始位置。</span></p></body></html>", None))
        self.label_6.setText(_translate("imneu_mainwindow", "肘部：", None))
        self.label_9.setText(_translate("imneu_mainwindow", "肩部L：", None))
        self.label_8.setText(_translate("imneu_mainwindow", "肩部M：", None))
        self.label_7.setText(_translate("imneu_mainwindow", "肩部U：", None))
        self.label_13.setText(_translate("imneu_mainwindow", "肘部：", None))
        self.label_12.setText(_translate("imneu_mainwindow", "肩部L:", None))
        self.label_11.setText(_translate("imneu_mainwindow", "肩部M:", None))
        self.label_10.setText(_translate("imneu_mainwindow", "肩部U：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("imneu_mainwindow", "手臂关节角度控制", None))
        self.label_4.setText(_translate("imneu_mainwindow", "左臂", None))
        self.label_5.setText(_translate("imneu_mainwindow", "右臂", None))
        self.textEdit_2.setHtml(_translate("imneu_mainwindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans Fallback\'; font-size:11pt;\">帮助：滑动滑块可以直接控制；输入x，y，z坐标点击执行控制；点击复位回到初始位置；中间位置显示关节角度信息。</span></p></body></html>", None))
        self.cartesian_reset_button.setText(_translate("imneu_mainwindow", "复位", None))
        self.cartesian_excute_button.setText(_translate("imneu_mainwindow", "执行", None))
        self.label_14.setText(_translate("imneu_mainwindow", "X:", None))
        self.label_17.setText(_translate("imneu_mainwindow", "Y:", None))
        self.label_16.setText(_translate("imneu_mainwindow", "Z:", None))
        self.label_15.setText(_translate("imneu_mainwindow", "X:", None))
        self.label_19.setText(_translate("imneu_mainwindow", "Y:", None))
        self.label_18.setText(_translate("imneu_mainwindow", "Z:", None))
        self.label_20.setText(_translate("imneu_mainwindow", "肘关节", None))
        self.label_21.setText(_translate("imneu_mainwindow", "肩关节1", None))
        self.label_23.setText(_translate("imneu_mainwindow", "肩关节2", None))
        self.label_22.setText(_translate("imneu_mainwindow", "肩关节3", None))
        self.label_24.setText(_translate("imneu_mainwindow", "肘关节", None))
        self.label_25.setText(_translate("imneu_mainwindow", "肩关节1", None))
        self.label_27.setText(_translate("imneu_mainwindow", "肩关节2", None))
        self.label_26.setText(_translate("imneu_mainwindow", "肩关节3", None))
        self.label_28.setText(_translate("imneu_mainwindow", "最小距离", None))
        self.label_29.setText(_translate("imneu_mainwindow", "最小距离", None))
        self.hand_open.setText(_translate("imneu_mainwindow", "手部张开", None))
        self.hand_half_closed.setText(_translate("imneu_mainwindow", "准备抓取", None))
        self.hand_closed.setText(_translate("imneu_mainwindow", "手部握紧", None))
        self.fangzhi_zhunbei.setText(_translate("imneu_mainwindow", "准备放置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("imneu_mainwindow", "笛卡尔坐标控制", None))
        self.label.setText(_translate("imneu_mainwindow", "imNEU控制交互界面", None))

